DO $$
	DECLARE _TEST JSON[];
BEGIN
	
	SELECT ARRAY_AGG(DATA) AS DATA
	INTO _TEST
	FROM 
	(
		SELECT 	ROW_NUMBER() OVER( ORDER BY 0 ) AS CNT
					,	JSON_BUILD_OBJECT('id',"MEMO_ID",'answer',CASE WHEN "MEMO_ID" % 2 = 0 THEN TRUE ELSE FALSE END) AS DATA
		FROM "TB_MEMO"
	) AS LIST
	WHERE LIST.CNT <= 10;

	UPDATE "TB_TEST_RESULT"
	SET "TEST_RESULT" = _TEST;
	
END $$;

SELECT *
FROM "TB_MEMO"
WHERE "MEMO_ID" NOT IN
(
	SELECT CAST(DATA ->> 'id' AS BIGINT)
	FROM 
	(
		SELECT UNNEST("TEST_RESULT") AS DATA
		FROM "TB_TEST_RESULT"
	) AS LIST
);



UPDATE "TB_TEST_RESULT"
SET "TEST_RESULT" = ARRAY[]::JSON[]